NAME = form

CFLAGS = -std=c++98 -Wall -Wextra -Werror

COM = c++

FILES = Intern.cpp ShrubberyCreationForm.cpp Form.cpp Bureaucrat.cpp main.cpp PresidentialPardonForm.cpp RobotomyRequestForm.cpp

all :
	$(COM) $(CFLAGS) $(FILES) -o $(NAME)

clean :
	rm $(NAME)