NAME = form

CFLAGS = -std=c++98 -Wall -Wextra -Werror

COM = c++

FILES = main.cpp Form.cpp PresidentialPardonForm.cpp ShrubberyCreationForm.cpp RobotomyRequestForm.cpp Bureaucrat.cpp

all :
	$(COM) $(CFLAGS) $(FILES) -o $(NAME)

clean :
	rm $(NAME)